version: '3.7'
services:
  api-server:
    container_name: api-server
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api-server
    #ここから追記
    depends_on:
      - db-server
  db-server:
    container_name: db-server
    image: mysql:5.7.29
    platform: linux/amd64
    restart: always
    ports:
      - '3306:3306'

    # MYSQLを永続化するために、volumesを追加する
    # volumes:
    #   - db_data:/var/lib/mysql

    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password

volumes:
  db_data:
